// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/repo/user_telegram_discord_association/store.go

// Package mock_usertelegramdiscordassociation is a generated GoMock package.
package mock_usertelegramdiscordassociation

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/defipod/mochi/pkg/model"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetOneByTelegramUsername mocks base method.
func (m *MockStore) GetOneByTelegramUsername(telegramID string) (*model.UserTelegramDiscordAssociation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByTelegramUsername", telegramID)
	ret0, _ := ret[0].(*model.UserTelegramDiscordAssociation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByTelegramUsername indicates an expected call of GetOneByTelegramUsername.
func (mr *MockStoreMockRecorder) GetOneByTelegramUsername(telegramID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByTelegramUsername", reflect.TypeOf((*MockStore)(nil).GetOneByTelegramUsername), telegramID)
}

// Upsert mocks base method.
func (m *MockStore) Upsert(arg0 *model.UserTelegramDiscordAssociation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockStoreMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockStore)(nil).Upsert), arg0)
}
