\ir users.sql
\ir discord_guilds.sql
\ir guild_users.sql
\ir nft_collections.sql
\ir activities.sql
\ir config_xp_levels.sql
\ir user_wallets.sql
\ir tokens.sql
\ir guild_config_tokens.sql
\ir upvote_streak_tiers.sql
\ir offchain_tip_bot.sql
\ir dao_guideline_messages.sql