version: "3"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mochi_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: mochi-postgres
    ports:
      - 5434:5432
    expose:
      - 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6-alpine
    restart: always
    container_name: mochi-redis
    ports:
      - 6379:6379
    expose:
      - 6379
  postgres_test:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mochi_local_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: mochi_local_test
    ports:
      - 25433:5432
    expose:
      - 25433

  chrome:
    image: browserless/chrome
    container_name: chrome
    restart: always
    ports:
      - 3000:3000

volumes:
  postgres_data:
