version: "3"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mochi_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: mochi-postgres
    ports:
      - 5434:5432
    expose:
      - 5434
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6-alpine
    restart: always
    container_name: mochi-redis
    ports:
      - 6379:6379
    expose:
      - 6379
  postgres_test:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mochi_local_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: mochi_local_test
    ports:
      - 25433:5432
    expose:
      - 25433

  chrome:
    image: browserless/chrome
    container_name: chrome
    restart: always
    ports:
      - 3000:3000

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    # ports:
    #   - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
# volumes:
#   postgres_data:
