// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/repo/offchain_tip_bot_contract/store.go

// Package mock_offchain_tip_bot_contract is a generated GoMock package.
package mock_offchain_tip_bot_contract

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/defipod/mochi/pkg/model"
	offchain_tip_bot_contract "github.com/defipod/mochi/pkg/repo/offchain_tip_bot_contract"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateAssignContract mocks base method.
func (m *MockStore) CreateAssignContract(ac *model.OffchainTipBotAssignContract) (*model.OffchainTipBotAssignContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAssignContract", ac)
	ret0, _ := ret[0].(*model.OffchainTipBotAssignContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAssignContract indicates an expected call of CreateAssignContract.
func (mr *MockStoreMockRecorder) CreateAssignContract(ac interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAssignContract", reflect.TypeOf((*MockStore)(nil).CreateAssignContract), ac)
}

// DeleteExpiredAssignContract mocks base method.
func (m *MockStore) DeleteExpiredAssignContract() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredAssignContract")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredAssignContract indicates an expected call of DeleteExpiredAssignContract.
func (mr *MockStoreMockRecorder) DeleteExpiredAssignContract() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredAssignContract", reflect.TypeOf((*MockStore)(nil).DeleteExpiredAssignContract))
}

// GetAssignContract mocks base method.
func (m *MockStore) GetAssignContract(address, tokenSymbol string) (*model.OffchainTipBotAssignContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignContract", address, tokenSymbol)
	ret0, _ := ret[0].(*model.OffchainTipBotAssignContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignContract indicates an expected call of GetAssignContract.
func (mr *MockStoreMockRecorder) GetAssignContract(address, tokenSymbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignContract", reflect.TypeOf((*MockStore)(nil).GetAssignContract), address, tokenSymbol)
}

// GetByAddress mocks base method.
func (m *MockStore) GetByAddress(addr string) (model.OffchainTipBotContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAddress", addr)
	ret0, _ := ret[0].(model.OffchainTipBotContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAddress indicates an expected call of GetByAddress.
func (mr *MockStoreMockRecorder) GetByAddress(addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAddress", reflect.TypeOf((*MockStore)(nil).GetByAddress), addr)
}

// GetByID mocks base method.
func (m *MockStore) GetByID(id string) (model.OffchainTipBotContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(model.OffchainTipBotContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStoreMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStore)(nil).GetByID), id)
}

// List mocks base method.
func (m *MockStore) List(arg0 offchain_tip_bot_contract.ListQuery) ([]model.OffchainTipBotContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]model.OffchainTipBotContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoreMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStore)(nil).List), arg0)
}
