// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/repo/quest_reward/store.go

// Package mock_questreward is a generated GoMock package.
package mock_questreward

import (
	reflect "reflect"

	model "github.com/defipod/mochi/pkg/model"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetQuestRewards mocks base method.
func (m *MockStore) GetQuestRewards(questID []uuid.UUID) ([]model.QuestReward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestRewards", questID)
	ret0, _ := ret[0].([]model.QuestReward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestRewards indicates an expected call of GetQuestRewards.
func (mr *MockStoreMockRecorder) GetQuestRewards(questID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestRewards", reflect.TypeOf((*MockStore)(nil).GetQuestRewards), questID)
}
