// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/service/abi/service.go

// Package mock_abi is a generated GoMock package.
package mock_abi

import (
	reflect "reflect"

	model "github.com/defipod/mochi/pkg/model"
	request "github.com/defipod/mochi/pkg/request"
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	types "github.com/ethereum/go-ethereum/core/types"
	ethclient "github.com/ethereum/go-ethereum/ethclient"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetNameAndSymbol mocks base method.
func (m *MockService) GetNameAndSymbol(address string, chainId int64) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNameAndSymbol", address, chainId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNameAndSymbol indicates an expected call of GetNameAndSymbol.
func (mr *MockServiceMockRecorder) GetNameAndSymbol(address, chainId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNameAndSymbol", reflect.TypeOf((*MockService)(nil).GetNameAndSymbol), address, chainId)
}

// PrepareTxOpts mocks base method.
func (m *MockService) PrepareTxOpts(client *ethclient.Client) (*bind.TransactOpts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareTxOpts", client)
	ret0, _ := ret[0].(*bind.TransactOpts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareTxOpts indicates an expected call of PrepareTxOpts.
func (mr *MockServiceMockRecorder) PrepareTxOpts(client interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareTxOpts", reflect.TypeOf((*MockService)(nil).PrepareTxOpts), client)
}

// SwapTokenOnKyber mocks base method.
func (m *MockService) SwapTokenOnKyber(req request.KyberSwapRequest) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwapTokenOnKyber", req)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SwapTokenOnKyber indicates an expected call of SwapTokenOnKyber.
func (mr *MockServiceMockRecorder) SwapTokenOnKyber(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwapTokenOnKyber", reflect.TypeOf((*MockService)(nil).SwapTokenOnKyber), req)
}

// SweepTokens mocks base method.
func (m *MockService) SweepTokens(contractAddr string, chainID int64, token model.Token) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepTokens", contractAddr, chainID, token)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepTokens indicates an expected call of SweepTokens.
func (mr *MockServiceMockRecorder) SweepTokens(contractAddr, chainID, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepTokens", reflect.TypeOf((*MockService)(nil).SweepTokens), contractAddr, chainID, token)
}
