// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/repo/nft_sales_tracker/store.go

// Package mock_nft_sales_tracker is a generated GoMock package.
package mock_nft_sales_tracker

import (
	reflect "reflect"

	model "github.com/defipod/mochi/pkg/model"
	response "github.com/defipod/mochi/pkg/response"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// DeleteNFTSalesTrackerByContractAddress mocks base method.
func (m *MockStore) DeleteNFTSalesTrackerByContractAddress(contractAddress string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNFTSalesTrackerByContractAddress", contractAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNFTSalesTrackerByContractAddress indicates an expected call of DeleteNFTSalesTrackerByContractAddress.
func (mr *MockStoreMockRecorder) DeleteNFTSalesTrackerByContractAddress(contractAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNFTSalesTrackerByContractAddress", reflect.TypeOf((*MockStore)(nil).DeleteNFTSalesTrackerByContractAddress), contractAddress)
}

// FirstOrCreate mocks base method.
func (m *MockStore) FirstOrCreate(arg0 *model.InsertNFTSalesTracker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FirstOrCreate indicates an expected call of FirstOrCreate.
func (mr *MockStoreMockRecorder) FirstOrCreate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreate", reflect.TypeOf((*MockStore)(nil).FirstOrCreate), arg0)
}

// GetAll mocks base method.
func (m *MockStore) GetAll() ([]model.NFTSalesTracker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.NFTSalesTracker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockStoreMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockStore)(nil).GetAll))
}

// GetSalesTrackerByGuildID mocks base method.
func (m *MockStore) GetSalesTrackerByGuildID(guildId string) ([]response.NFTSalesTrackerData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesTrackerByGuildID", guildId)
	ret0, _ := ret[0].([]response.NFTSalesTrackerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalesTrackerByGuildID indicates an expected call of GetSalesTrackerByGuildID.
func (mr *MockStoreMockRecorder) GetSalesTrackerByGuildID(guildId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesTrackerByGuildID", reflect.TypeOf((*MockStore)(nil).GetSalesTrackerByGuildID), guildId)
}

// GetStarTrackerByGuildID mocks base method.
func (m *MockStore) GetStarTrackerByGuildID(guildId string) (*model.NFTSalesTracker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStarTrackerByGuildID", guildId)
	ret0, _ := ret[0].(*model.NFTSalesTracker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStarTrackerByGuildID indicates an expected call of GetStarTrackerByGuildID.
func (mr *MockStoreMockRecorder) GetStarTrackerByGuildID(guildId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStarTrackerByGuildID", reflect.TypeOf((*MockStore)(nil).GetStarTrackerByGuildID), guildId)
}
