bin: git
style: "github"
info:
  title: CHANGELOG
  repository_url: https://github.com/consolelabs/mochi-api.git
options:
  tag_filter_pattern: '^v'
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - chore
    sort_by: Scope
  commit_groups:
    group_by: Type
    sort_by: Title
    title_order:
      - feat
      - fix
      - perf
      - refactor
      - chore
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      chore: Chores
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE