// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/repo/guild_config_repost_reaction/store.go

// Package mock_guild_config_repost_reaction is a generated GoMock package.
package mock_guild_config_repost_reaction

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/defipod/mochi/pkg/model"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// DeleteConfigConversation mocks base method.
func (m *MockStore) DeleteConfigConversation(guildID, emojiStart, emojiStop string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfigConversation", guildID, emojiStart, emojiStop)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfigConversation indicates an expected call of DeleteConfigConversation.
func (mr *MockStoreMockRecorder) DeleteConfigConversation(guildID, emojiStart, emojiStop interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfigConversation", reflect.TypeOf((*MockStore)(nil).DeleteConfigConversation), guildID, emojiStart, emojiStop)
}

// DeleteConfigMessage mocks base method.
func (m *MockStore) DeleteConfigMessage(guildID, emoji string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfigMessage", guildID, emoji)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfigMessage indicates an expected call of DeleteConfigMessage.
func (mr *MockStoreMockRecorder) DeleteConfigMessage(guildID, emoji interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfigMessage", reflect.TypeOf((*MockStore)(nil).DeleteConfigMessage), guildID, emoji)
}

// GetByGuildID mocks base method.
func (m *MockStore) GetByGuildID(guildID string) ([]model.GuildConfigRepostReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGuildID", guildID)
	ret0, _ := ret[0].([]model.GuildConfigRepostReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGuildID indicates an expected call of GetByGuildID.
func (mr *MockStoreMockRecorder) GetByGuildID(guildID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGuildID", reflect.TypeOf((*MockStore)(nil).GetByGuildID), guildID)
}

// GetByGuildIDAndReactionType mocks base method.
func (m *MockStore) GetByGuildIDAndReactionType(guildID, reactionType string) ([]model.GuildConfigRepostReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGuildIDAndReactionType", guildID, reactionType)
	ret0, _ := ret[0].([]model.GuildConfigRepostReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGuildIDAndReactionType indicates an expected call of GetByGuildIDAndReactionType.
func (mr *MockStoreMockRecorder) GetByGuildIDAndReactionType(guildID, reactionType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGuildIDAndReactionType", reflect.TypeOf((*MockStore)(nil).GetByGuildIDAndReactionType), guildID, reactionType)
}

// GetByReaction mocks base method.
func (m *MockStore) GetByReaction(guildID, reaction string) (model.GuildConfigRepostReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReaction", guildID, reaction)
	ret0, _ := ret[0].(model.GuildConfigRepostReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReaction indicates an expected call of GetByReaction.
func (mr *MockStoreMockRecorder) GetByReaction(guildID, reaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReaction", reflect.TypeOf((*MockStore)(nil).GetByReaction), guildID, reaction)
}

// GetByReactionConversationStartOrStop mocks base method.
func (m *MockStore) GetByReactionConversationStartOrStop(guildID, emoji string) (model.GuildConfigRepostReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReactionConversationStartOrStop", guildID, emoji)
	ret0, _ := ret[0].(model.GuildConfigRepostReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReactionConversationStartOrStop indicates an expected call of GetByReactionConversationStartOrStop.
func (mr *MockStoreMockRecorder) GetByReactionConversationStartOrStop(guildID, emoji interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReactionConversationStartOrStop", reflect.TypeOf((*MockStore)(nil).GetByReactionConversationStartOrStop), guildID, emoji)
}

// GetByReactionStartOrStop mocks base method.
func (m *MockStore) GetByReactionStartOrStop(guildID, emoji string) (model.GuildConfigRepostReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReactionStartOrStop", guildID, emoji)
	ret0, _ := ret[0].(model.GuildConfigRepostReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReactionStartOrStop indicates an expected call of GetByReactionStartOrStop.
func (mr *MockStoreMockRecorder) GetByReactionStartOrStop(guildID, emoji interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReactionStartOrStop", reflect.TypeOf((*MockStore)(nil).GetByReactionStartOrStop), guildID, emoji)
}

// GetByRepostChannelID mocks base method.
func (m *MockStore) GetByRepostChannelID(guildID, channelID string) (model.GuildConfigRepostReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRepostChannelID", guildID, channelID)
	ret0, _ := ret[0].(model.GuildConfigRepostReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRepostChannelID indicates an expected call of GetByRepostChannelID.
func (mr *MockStoreMockRecorder) GetByRepostChannelID(guildID, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRepostChannelID", reflect.TypeOf((*MockStore)(nil).GetByRepostChannelID), guildID, channelID)
}

// UpsertOne mocks base method.
func (m *MockStore) UpsertOne(config model.GuildConfigRepostReaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertOne", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertOne indicates an expected call of UpsertOne.
func (mr *MockStoreMockRecorder) UpsertOne(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertOne", reflect.TypeOf((*MockStore)(nil).UpsertOne), config)
}
