// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/repo/guild_user_xp/store.go

// Package mock_guild_user_xp is a generated GoMock package.
package mock_guild_user_xp

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/defipod/mochi/pkg/model"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetByGuildID mocks base method.
func (m *MockStore) GetByGuildID(guildID string) ([]model.GuildUserXP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGuildID", guildID)
	ret0, _ := ret[0].([]model.GuildUserXP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGuildID indicates an expected call of GetByGuildID.
func (mr *MockStoreMockRecorder) GetByGuildID(guildID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGuildID", reflect.TypeOf((*MockStore)(nil).GetByGuildID), guildID)
}

// GetOne mocks base method.
func (m *MockStore) GetOne(guildID, userID string) (*model.GuildUserXP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", guildID, userID)
	ret0, _ := ret[0].(*model.GuildUserXP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockStoreMockRecorder) GetOne(guildID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockStore)(nil).GetOne), guildID, userID)
}

// GetTopUsers mocks base method.
func (m *MockStore) GetTopUsers(guildID string, limit, offset int) ([]model.GuildUserXP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopUsers", guildID, limit, offset)
	ret0, _ := ret[0].([]model.GuildUserXP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopUsers indicates an expected call of GetTopUsers.
func (mr *MockStoreMockRecorder) GetTopUsers(guildID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopUsers", reflect.TypeOf((*MockStore)(nil).GetTopUsers), guildID, limit, offset)
}
