// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/repo/offchain_tip_bot_activity_logs/store.go

// Package mock_offchain_tip_bot_activity_logs is a generated GoMock package.
package mock_offchain_tip_bot_activity_logs

import (
	reflect "reflect"

	model "github.com/defipod/mochi/pkg/model"
	offchain_tip_bot_activity_logs "github.com/defipod/mochi/pkg/repo/offchain_tip_bot_activity_logs"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateActivityLog mocks base method.
func (m *MockStore) CreateActivityLog(al *model.OffchainTipBotActivityLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivityLog", al)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateActivityLog indicates an expected call of CreateActivityLog.
func (mr *MockStoreMockRecorder) CreateActivityLog(al interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivityLog", reflect.TypeOf((*MockStore)(nil).CreateActivityLog), al)
}

// List mocks base method.
func (m *MockStore) List(arg0 offchain_tip_bot_activity_logs.ListQuery) ([]model.OffchainTipBotActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]model.OffchainTipBotActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoreMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStore)(nil).List), arg0)
}
