on: [pull_request]

jobs:
  ci-test:
    runs-on: ubuntu-latest
    name: CI testing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20"

      - name: Init Test DB
        run: make init

      - name: Run Test cases
        run: make test
