on: [pull_request]

jobs:
  ci-test:
    runs-on: ubuntu-latest
    
    # Service containers to run with `container-job`
    services:
      # pg test
      postgres:
        # Docker Hub image
        image: postgres:15
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mochi_local_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 25433:5432      
      # pg local
      postgres_local:
        # Docker Hub image
        image: postgres:15
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mochi_local
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5434:5432      
      # chrome
      chrome:
        # Docker Hub image
        image: browserless/chrome
        ports:
          - 3000:3000
      # redis
      redis:
        image: redis:6
        ports:
          - 6379:6379

    name: CI testing
    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod
      - name: Install
        run: go install github.com/rubenv/sql-migrate/sql-migrate@latest
      - name: Migrate pg local
        run: make migrate-up
      - name: Run Test cases
        run: make test
