name: Dev - API - Build, Push and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - cicd
    paths:
      - api/**
      - .github/**

# Environment variables available to all jobs and steps in this workflow
env:
  ECR_API_REPOSITORY: mochi/api
  IMAGE_TAG: ${{ github.sha }}
  K8S_ENVIRONMENT: dev

permissions:
  id-token: write # This is required for authenticating with AWS using OIDC
  contents: read # This is required for actions/checkout

jobs:
  build_publish_api:
    name: Build & Publish API Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: API - Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --no-cache --pull -t $ECR_REGISTRY/$ECR_API_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_API_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_API_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_API_REPOSITORY:${GITHUB_REF##*/}
          docker push $ECR_REGISTRY/$ECR_API_REPOSITORY:${GITHUB_REF##*/}

  trigger_deployment:
    name: Trigger deployment
    runs-on: ubuntu-latest
    needs: [build_publish_api]
    steps:
      # Setup kustomize
      - name: Setup kustomize
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          mv kustomize /tmp
      - name: Checkout consolelabs/infrastructure
        uses: actions/checkout@master
        with:
          repository: consolelabs/infrastructure
          token: ${{ secrets.GH_PAT }}
          path: ./infrastructure
          ref: main
      - name: Update api version
        run: |
          cd ./infrastructure/mochi-api/$K8S_ENVIRONMENT
          git config user.name jphuc96
          git config user.email jphuc96@gmail.com
          /tmp/kustomize edit set image $ECR_REGISTRY/$ECR_API_REPOSITORY=$ECR_REGISTRY/$ECR_API_REPOSITORY:${GITHUB_SHA}
          git commit -am "[skip ci] mochi-api ${K8S_ENVIRONMENT} image update"
          git push origin main